### ISSUE TITLE
Design new emotes

### ISSUE THREAD

**Issue by JustYourBud** [BudWorks/Akaei#66]
Right now, Akaei has 3+ years worth of emotes all over the UI of the bot. Some embeds use emotes designed after Akaei's style and identity were more polished, while others are still around from 2019. In order to make the bot feel more unified, all of the custom emotes should be redesigned from scratch with Akaei's modern identity in mind.

## Issues and Tasks
- [ ] Redesign emotes used in messages and embeds
- [ ] Redesign emotes used in reactions, buttons, menus, etc.
- [ ] Redesign emotes used for pets, items, etc.
- [ ] Design new emotes to be used in certain situations
